/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BoardImport } from './routes/board'
import { Route as IndexImport } from './routes/index'
import { Route as BoardStressImport } from './routes/board.stress'
import { Route as BoardApiImport } from './routes/board.api'

// Create/Update Routes

const BoardRoute = BoardImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BoardStressRoute = BoardStressImport.update({
  id: '/stress',
  path: '/stress',
  getParentRoute: () => BoardRoute,
} as any)

const BoardApiRoute = BoardApiImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => BoardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardImport
      parentRoute: typeof rootRoute
    }
    '/board/api': {
      id: '/board/api'
      path: '/api'
      fullPath: '/board/api'
      preLoaderRoute: typeof BoardApiImport
      parentRoute: typeof BoardImport
    }
    '/board/stress': {
      id: '/board/stress'
      path: '/stress'
      fullPath: '/board/stress'
      preLoaderRoute: typeof BoardStressImport
      parentRoute: typeof BoardImport
    }
  }
}

// Create and export the route tree

interface BoardRouteChildren {
  BoardApiRoute: typeof BoardApiRoute
  BoardStressRoute: typeof BoardStressRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardApiRoute: BoardApiRoute,
  BoardStressRoute: BoardStressRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/board/api': typeof BoardApiRoute
  '/board/stress': typeof BoardStressRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/board/api': typeof BoardApiRoute
  '/board/stress': typeof BoardStressRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/board/api': typeof BoardApiRoute
  '/board/stress': typeof BoardStressRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/board/api' | '/board/stress'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/board/api' | '/board/stress'
  id: '__root__' | '/' | '/board' | '/board/api' | '/board/stress'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/board"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/board": {
      "filePath": "board.tsx",
      "children": [
        "/board/api",
        "/board/stress"
      ]
    },
    "/board/api": {
      "filePath": "board.api.tsx",
      "parent": "/board"
    },
    "/board/stress": {
      "filePath": "board.stress.tsx",
      "parent": "/board"
    }
  }
}
ROUTE_MANIFEST_END */
